'use strict';
const $=id=>document.getElementById(id),G=SnackGame,KEY='trelum-snack-catch-best-v2';
const arena=$('arena'),player=$('player');let round=G.create(),mode='idle',best=0,frame=0,lastTime=0,geometry={edge:.1,catchWidth:.09,catchY:.88},sound=true,audio,poseTimer,hintTimer,keys=new Set(),nodeMap=new Map(),effectTimers=new Set();
try{best=G.readBest(localStorage.getItem(KEY));}catch{}$('best').textContent=best;
const fish='<svg viewBox="0 0 60 38"><defs><linearGradient id="fish" x2=".3" y2="1"><stop stop-color="#f9d28b"/><stop offset=".5" stop-color="#eaa04b"/><stop offset="1" stop-color="#b66b29"/></linearGradient></defs><path d="M45 19L57 6L56 32Z" fill="#ce8638"/><ellipse cx="27" cy="19" rx="22" ry="15" fill="url(#fish)" stroke="#ac672a" stroke-width="1"/><path d="M13 10Q29 2 41 13" fill="none" stroke="#ffe8b4" stroke-width="2"/><circle cx="15" cy="16" r="2.2" fill="#533d27"/><path d="M29 11L22 19L29 26M39 12L32 19L39 25" fill="none" stroke="#b9742d" stroke-width="1.4"/></svg>';
function measure(){const board=arena.getBoundingClientRect(),bowl=player.querySelector('.bowl').getBoundingClientRect();geometry={edge:Math.max(.07,bowl.width*.5/board.width+.012),catchWidth:(bowl.width*.38+(board.width<620?9:12))/board.width,catchY:(bowl.top+bowl.height*.33-board.top)/board.height};}
function updateHud(){ $('score').textContent=round.score;$('best').textContent=best;$('lives').setAttribute('aria-label',(3-round.misses)+' misses left');[...$('lives').children].forEach((el,i)=>el.classList.toggle('lost',i>=3-round.misses));}
function tone(miss=false){if(!sound)return;try{audio ||= new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const o=audio.createOscillator(),gain=audio.createGain();o.connect(gain);gain.connect(audio.destination);o.type='sine';o.frequency.setValueAtTime(miss?200:610+Math.min(round.streak,8)*38,audio.currentTime);o.frequency.exponentialRampToValueAtTime(miss?120:880,audio.currentTime+.11);gain.gain.setValueAtTime(.04,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.start();o.stop(audio.currentTime+.18);o.onended=()=>{o.disconnect();gain.disconnect();};}catch{}}
function clearEffects(){effectTimers.forEach(clearTimeout);effectTimers.clear();$('effects').replaceChildren();clearTimeout(poseTimer);clearTimeout(hintTimer);player.className='player';$('combo').className='combo';arena.classList.remove('hit');}
function effect(e){const el=document.createElement('span');el.className='effect';el.textContent=e.type==='catch'?'+1':'·';el.style.left=e.x*100+'%';el.style.top=(e.y*100-7)+'%';if(e.type==='miss')el.style.color='#b05035';$('effects').append(el);const t=setTimeout(()=>{el.remove();effectTimers.delete(t);},700);effectTimers.add(t);}
function drawDrops(){const active=new Set(round.drops.map(d=>d.id));for(const [id,n]of nodeMap)if(!active.has(id)){n.remove();nodeMap.delete(id);}const w=arena.clientWidth,h=arena.clientHeight;for(const d of round.drops){let n=nodeMap.get(d.id);if(!n){n=document.createElement('div');n.className='treat';n.innerHTML=fish;$('drops').append(n);nodeMap.set(d.id,n);}n.style.transform=`translate(${d.x*w-n.offsetWidth/2}px,${d.y*h-n.offsetHeight/2}px) rotate(${d.rotation}deg)`;}}
function saveBest(){if(round.score<=best)return false;best=round.score;try{localStorage.setItem(KEY,String(best));}catch{$('below-note').textContent='Best score cannot save in this browser.';}return true;}
function end(){mode='ended';cancelAnimationFrame(frame);keys.clear();const record=saveBest();arena.className='arena finished';$('overlay').hidden=false;$('intro').hidden=true;$('paused').hidden=true;$('result').hidden=false;$('pause').disabled=true;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause game');$('final-score').textContent=round.score;$('result-tag').textContent=record?'A NEW PERSONAL BEST':round.score>=15?'QUICK PAWS!':'NICE CATCHES';$('result-title').textContent=record?'That’s a record.':round.score===0?'One more try?':'One more?';$('result-note').textContent=round.score===0?'Follow the fish with your bowl. You’ve got this.':round.score>=20?'Mochi has excellent taste in teammates.':'Mochi’s ready for another round.';$('announcement').textContent=`Game over. ${round.score} snacks caught. Best ${best}.`;clearEffects();round.drops=[];drawDrops();updateHud();$('restart').focus({preventScroll:true});}
function onEvent(e){if(e.type==='end'){end();return;}effect(e);clearTimeout(poseTimer);player.className='player '+(e.type==='catch'?'caught':'missed');poseTimer=setTimeout(()=>{player.className='player';},340);tone(e.type==='miss');if(e.type==='catch'){$('move-hint').hidden=true;if(round.score%5===0){$('combo').textContent=['Nice paws!','Faster now!','On a roll!','Unstoppable!'][Math.min(3,Math.floor(round.score/5)-1)];$('combo').className='combo';void $('combo').offsetWidth;$('combo').className='combo show';$('announcement').textContent=`${round.score} snacks! Getting faster.`;}}else{arena.classList.remove('hit');void arena.offsetWidth;arena.classList.add('hit');$('announcement').textContent=`Missed. ${3-round.misses} chances left.`;}updateHud();}
function tick(time){if(mode!=='playing')return;const dt=lastTime?Math.min(.05,(time-lastTime)/1000):0;lastTime=time;if(keys.has('left'))round.target-=dt*1.25;if(keys.has('right'))round.target+=dt*1.25;const events=G.step(round,dt,geometry);player.style.left=round.x*100+'%';drawDrops();events.forEach(onEvent);if(mode==='playing')frame=requestAnimationFrame(tick);}
function begin(){cancelAnimationFrame(frame);round=G.create();mode='playing';lastTime=0;keys.clear();clearEffects();arena.className='arena playing';$('overlay').hidden=true;$('intro').hidden=true;$('result').hidden=true;$('paused').hidden=true;$('move-hint').hidden=false;$('pause').disabled=false;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause game');$('announcement').textContent='Go! Move left and right. Catch the fish. Three misses ends the round.';player.style.left='50%';nodeMap.forEach(n=>n.remove());nodeMap.clear();measure();updateHud();arena.focus({preventScroll:true});hintTimer=setTimeout(()=>{$('move-hint').hidden=true;},7500);frame=requestAnimationFrame(tick);tone();}
function pause(){if(mode==='paused'){resume();return;}if(mode!=='playing')return;mode='paused';cancelAnimationFrame(frame);keys.clear();arena.className='arena paused';$('overlay').hidden=false;$('paused').hidden=false;$('intro').hidden=true;$('result').hidden=true;$('pause').textContent='▶';$('pause').setAttribute('aria-label','Resume game');$('announcement').textContent='Game paused.';$('resume').focus({preventScroll:true});}
function resume(){if(mode!=='paused')return;mode='playing';lastTime=0;arena.className='arena playing';$('overlay').hidden=true;$('paused').hidden=true;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause game');measure();arena.focus({preventScroll:true});frame=requestAnimationFrame(tick);}
function aim(clientX){if(mode!=='playing')return;const rect=arena.getBoundingClientRect();round.target=G.clamp((clientX-rect.left)/rect.width,geometry.edge,1-geometry.edge);}
arena.addEventListener('pointerdown',e=>{if(mode!=='playing')return;aim(e.clientX);arena.setPointerCapture(e.pointerId);});arena.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||e.buttons)aim(e.clientX);});
function direction(e){if(['ArrowLeft','a','A'].includes(e.key))return'left';if(['ArrowRight','d','D'].includes(e.key))return'right';}
document.addEventListener('keydown',e=>{const d=direction(e);if(mode==='playing'&&d){e.preventDefault();keys.add(d);}if((mode==='playing'||mode==='paused')&&(e.key==='Escape'||e.code==='Space')&&!e.repeat&&!(e.target instanceof HTMLButtonElement)){e.preventDefault();pause();}});document.addEventListener('keyup',e=>{const d=direction(e);if(d)keys.delete(d);});
for(const d of ['left','right']){const b=$(d);b.addEventListener('pointerdown',e=>{if(mode!=='playing')return;e.preventDefault();keys.add(d);b.setPointerCapture(e.pointerId);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(d));b.addEventListener('click',e=>{if(mode==='playing'&&e.detail===0)round.target+=d==='left'?-.15:.15;});}
window.addEventListener('blur',()=>{keys.clear();if(mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});window.addEventListener('resize',()=>{if(mode==='playing'||mode==='paused')measure();});
$('start').onclick=begin;$('restart').onclick=begin;$('pause').onclick=pause;$('resume').onclick=resume;$('quit').onclick=end;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫':'♪';$('sound').setAttribute('aria-label',sound?'Sound on':'Sound off');$('sound').setAttribute('aria-pressed',String(sound));if(sound)tone();};updateHud();
