'use strict';
const $=id=>document.getElementById(id),W=WorldState,KEY='trelum-mochi-world-v1';
let pet=W.fresh();try{pet=W.load(JSON.parse(localStorage.getItem(KEY)));}catch{}
let busy=false,sound=true,audio,animationTimer,gameGeneration=0,deck=[],flipped=[],matched=new Set(),turns=0,gameBusy=false,won=false;
const taskNames={feed:'Share a crunchy snack',cuddle:'Give a little cuddle',rest:'Take a cozy nap',match:'Play snack match'};
const badges={hello:{icon:'♡',name:'First cuddle'},matcher:{icon:'✿',name:'Match maker'},designer:{icon:'❀',name:'Room designer'},buddy:{icon:'✦',name:'Best buddies'}};
const icons={plant:'🌿',rug:'☀',hat:'🍓',lamp:'☾'};
function save(){try{localStorage.setItem(KEY,JSON.stringify(pet));$('save-status').textContent='Your little world saves on this device.';}catch{$('save-status').textContent='Saving is unavailable. Use Settings → Download my world to keep your progress.';}}
function chirp(type='good'){if(!sound)return;try{audio ||= new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});[0,.1].forEach((d,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.value=(type==='match'?690:510)+i*110;g.gain.setValueAtTime(.035,audio.currentTime+d);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d+.16);o.start(audio.currentTime+d);o.stop(audio.currentTime+d+.18);o.onended=()=>{o.disconnect();g.disconnect();};});}catch{}}
function say(text){$('speech').textContent=text;}
function render(){const level=Math.floor(pet.xp/40)+1;$('coins').textContent=pet.coins;$('pet-name').textContent=pet.name;$('day').textContent='ADVENTURE '+String(pet.day).padStart(2,'0');$('level').textContent='Lv. '+level;$('level-name').textContent=level===1?'New friend':level===2?'Little buddy':level===3?'Best friend':'Forever friends';$('bond-label').textContent=`Friendship · ${pet.xp%40} / 40`;$('bond').value=pet.xp%40;for(const k of ['fullness','energy','joy']){$(k).value=pet[k];$(k+'-text').textContent=pet[k]+'%';}$('tasks').replaceChildren();Object.entries(taskNames).forEach(([key,label])=>{const li=document.createElement('li');li.className=pet.tasks.includes(key)?'done':'';const marker=document.createElement('span');marker.textContent=pet.tasks.includes(key)?'✓':'·';const text=document.createElement('span');text.className='task-name';text.textContent=label;const reward=document.createElement('b');reward.textContent=pet.tasks.includes(key)?'Done':'+3 ✦';li.append(marker,text,reward);$('tasks').append(li);});$('task-count').textContent=pet.tasks.length+' / 4';$('next-day').hidden=pet.tasks.length!==4;$('daily-note').textContent=pet.tasks.length===4?'A lovely day together! Open a new adventure for 10 bonus coins.':'Your bunny is safe and happy while you’re away.';
$('shop-items').replaceChildren();Object.entries(W.items).forEach(([key,item])=>{const b=document.createElement('button');b.className=pet.equipped.includes(key)?'active':'';const icon=document.createElement('span');icon.className='item-icon';icon.textContent=icons[key];const title=document.createElement('b');title.textContent=item.name;const price=document.createElement('small');price.textContent=pet.owned.includes(key)?pet.equipped.includes(key)?'In your room ✓':'Use this':'✦ '+item.price;b.append(icon,title,price);b.setAttribute('aria-label',`${item.name}, ${price.textContent}`);b.onclick=()=>buy(key);$('shop-items').append(b);});$('badges').replaceChildren();Object.entries(badges).forEach(([key,item])=>{const el=document.createElement('div');el.className='badge'+(pet.badges.includes(key)?' earned':'');const icon=document.createElement('span');icon.textContent=pet.badges.includes(key)?item.icon:'?';el.append(icon,document.createTextNode(item.name));el.title=pet.badges.includes(key)?'Collected!':'A little moment to discover';$('badges').append(el);});decorate();}
function decorate(){$('room').className='room '+pet.theme;document.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===pet.theme)));$('room-caption').textContent={meadow:'MEADOW MORNING',peach:'PEACH AFTERNOON',night:'MOONLIT EVENING'}[pet.theme];let art='';if(pet.equipped.includes('rug'))art+='<ellipse cx="260" cy="329" rx="138" ry="29" fill="#efd29a" stroke="#c8a97e" stroke-width="3"/><path d="M160 329H360 M176 314H344 M176 344H344" stroke="#d5b16c" stroke-width="2"/>';
// Place rug behind the bunny; the other treasures sit beside it.
let rug=$('rug-art');if(!rug){rug=document.createElementNS('http://www.w3.org/2000/svg','g');rug.id='rug-art';$('bunny').before(rug);}rug.innerHTML=art;let furniture='';if(pet.equipped.includes('plant'))furniture+='<path d="M418 321H467L459 354H426Z" fill="#d9552b" stroke="#a7653c" stroke-width="2"/><path d="M443 323V250" stroke="#4f6b3a" stroke-width="4"/><path d="M443 283Q401 271 412 246Q446 249 443 283 M443 297Q484 282 477 261Q446 265 443 297 M443 260Q436 230 451 224Q469 237 443 260" fill="#7d8c3f"/>';
if(pet.equipped.includes('lamp'))furniture+='<path d="M80 330V270" stroke="#4f6b3a" stroke-width="4"/><circle cx="80" cy="251" r="28" fill="#eed596" stroke="#c8a97e" stroke-width="3"/><path d="M90 230A23 23 0 1 0 90 271A28 28 0 0 1 90 230" fill="#e0a32a"/><path d="M62 334H98" stroke="#4f6b3a" stroke-width="5" stroke-linecap="round"/>';$('furniture').innerHTML=furniture;$('hat').innerHTML=pet.equipped.includes('hat')?'<path d="M217 180Q255 128 292 180Z" fill="#d9552b" stroke="#aa6a46" stroke-width="2"/><ellipse cx="255" cy="180" rx="44" ry="8" fill="#d9552b"/><path d="M251 143L238 132L254 133L265 121L264 139L277 137L263 151Z" fill="#7d8c3f"/><path d="M238 161l2 4 M258 160l2 4 M272 169l2 4" stroke="#faf6ee" stroke-width="3"/>':'';}
function animate(action){busy=true;for(const id of ['feed','rest','pet-tap','next-day'])$(id).disabled=true;clearTimeout(animationTimer);$('bunny').setAttribute('class','bunny '+action);$('eyes').innerHTML=action==='rest'?'<path d="M221 215q6 6 12 0 M276 215q6 6 12 0" fill="none" stroke="#33452a" stroke-width="3" stroke-linecap="round"/>':'<circle cx="227" cy="215" r="5" fill="#33452a"/><circle cx="282" cy="215" r="5" fill="#33452a"/>';$('prop').innerHTML=action==='feed'?'<path d="M278 276L296 259L316 294Z" fill="#d9552b"/><path d="M289 260l2-18 M296 259l14-14" stroke="#7d8c3f" stroke-width="5" stroke-linecap="round"/>':action==='rest'?'<text x="320" y="170" fill="#4f6b3a" font-family="Georgia" font-size="27">z z</text>':'';$('sparkles').innerHTML=action==='cuddle'||action==='play'?'<g class="spark"><text x="320" y="205" fill="#d9552b" font-size="32">♡</text><text x="167" y="182" fill="#e0a32a" font-size="24">✦</text></g>':'';animationTimer=setTimeout(()=>{$('bunny').setAttribute('class','bunny');$('prop').innerHTML='';$('sparkles').innerHTML='';$('eyes').innerHTML='<circle cx="227" cy="215" r="5" fill="#33452a"/><circle cx="282" cy="215" r="5" fill="#33452a"/>';busy=false;for(const id of ['feed','rest','pet-tap','next-day'])$(id).disabled=false;},action==='rest'?1800:1200);}
function care(action){if(busy)return;const previous=Math.floor(pet.xp/40),r=W.care(pet,action);if(!r.changed){say({feed:'My tummy is full. Maybe a game together?',rest:'All recharged! Let’s do something fun.',cuddle:'So much love! Shall we play a little game?'}[action]);return;}busy=true;pet=r.state;save();render();animate(action);chirp();const lines={feed:['Crunch, crunch. Carrots are my favourite!','That was delicious. Thank you, human.'],rest:['A cozy nap… wake me when the carrots arrive.','Just resting my fluffy little feet.'],cuddle:['Oh! You found my favourite cuddle spot.','If I could, I’d give you a hug right back.','You + me = a very lovely day.']};say(lines[action][Math.floor(Math.random()*lines[action].length)]);if(Math.floor(pet.xp/40)>previous)say('Our friendship grew! A new level of lovely. ♡');}
function buy(key){const r=W.buy(pet,key);if(r.error){$('shop-message').textContent=`A few more coins for ${W.items[key].name}. Play snack match to earn 12!`;chirp();return;}pet=r.state;save();render();$('shop-message').textContent=r.purchased?`${W.items[key].name} is yours. Home is getting cozier!`:pet.equipped.includes(key)?'A lovely choice!':'Tucked away safely. Tap it to use it again.';say(key==='hat'&&pet.equipped.includes(key)?'A strawberry hat?! I feel berry special.':'You make this little place feel like home.');chirp('match');}
const symbols=[{icon:'🥕',name:'Carrot'},{icon:'🍓',name:'Strawberry'},{icon:'🌿',name:'Leaf'},{icon:'🍄',name:'Mushroom'}];
function startRound(){gameGeneration++;deck=[0,0,1,1,2,2,3,3];for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}flipped=[];matched=new Set();turns=0;gameBusy=false;won=false;$('again').hidden=true;$('game-message').textContent='Pick two cards. Take your time — there’s no clock.';drawCards();}
function drawCards(){const focused=document.activeElement?.dataset?.card;$('memory-grid').replaceChildren();deck.forEach((kind,i)=>{const button=document.createElement('button');button.dataset.card=i;const revealed=flipped.includes(i)||matched.has(i);button.textContent=revealed?symbols[kind].icon:'✿';button.className=matched.has(i)?'matched':revealed?'flipped':'';button.setAttribute('aria-label',matched.has(i)?`${symbols[kind].name}, matched card ${i+1}`:revealed?`${symbols[kind].name}, card ${i+1}`:`Hidden card ${i+1}`);button.disabled=matched.has(i)||gameBusy;button.onclick=()=>flip(i);$('memory-grid').append(button);});$('pairs').textContent=matched.size/2+' / 4 pairs';$('moves').textContent=turns+' turns';if(focused!==undefined){const el=$('memory-grid').querySelector(`[data-card="${focused}"]`);if(el&&!el.disabled)el.focus();}}
async function flip(i){if(gameBusy||won||flipped.includes(i)||matched.has(i))return;flipped.push(i);chirp();if(flipped.length===1){drawCards();return;}turns++;gameBusy=true;drawCards();const generation=gameGeneration;const same=deck[flipped[0]]===deck[flipped[1]];await new Promise(r=>setTimeout(r,same?450:950));if(generation!==gameGeneration)return;if(same){flipped.forEach(x=>matched.add(x));$('game-message').textContent=['A lovely pair!','You found them!','Mochi does a little happy hop.'][Math.floor(Math.random()*3)];chirp('match');}else $('game-message').textContent='Not a pair. Remember where they are and try again.';flipped=[];gameBusy=false;drawCards();if(matched.size===8&&!won){won=true;pet=W.matchWin(pet);save();render();animate('play');say('You found all my snacks! Best playdate ever.');$('game-message').textContent=`All four pairs! +12 coins, +12 friendship. ${turns===4?'A perfect round!':'Mochi is doing a happy dance.'}`;$('again').hidden=false;chirp('match');$('again').focus();}}
function closeGame(){gameGeneration++;gameBusy=false;flipped=[];$('game-dialog').close();}
$('pet-tap').onclick=()=>care('cuddle');$('feed').onclick=()=>care('feed');$('rest').onclick=()=>care('rest');$('play').onclick=()=>{startRound();$('game-dialog').showModal();};$('close-game').onclick=closeGame;$('game-dialog').addEventListener('cancel',()=>{gameGeneration++;gameBusy=false;flipped=[];});$('again').onclick=startRound;$('wallet').onclick=()=>{$('shop-items').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'center'});$('shop-items').querySelector('button').focus({preventScroll:true});};
$('next-day').onclick=()=>{if(busy)return;pet=W.newDay(pet);save();render();say('A whole new day for us. Where shall we start?');chirp('match');};document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{pet.theme=b.dataset.theme;save();render();say({meadow:'Morning light and a pocket full of possibilities.',peach:'Golden afternoons are made for friends.',night:'The moon is out. Everything feels a little magical.'}[pet.theme]);});
$('rename').onclick=()=>{$('name-input').value=pet.name;$('name-dialog').showModal();};$('close-name').onclick=()=>$('name-dialog').close();$('name-form').onsubmit=e=>{e.preventDefault();const name=$('name-input').value.trim();if(!name){$('name-input').setCustomValidity('Give your bunny a name.');$('name-input').reportValidity();return;}$('name-input').setCustomValidity('');pet.name=name.slice(0,24);save();render();$('name-dialog').close();say(`That’s me! ${pet.name}. Your little friend.`);};$('name-input').oninput=()=>$('name-input').setCustomValidity('');$('settings').onclick=()=>$('settings-dialog').showModal();$('close-settings').onclick=()=>$('settings-dialog').close();$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫':'♪';$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Sound on':'Sound off');if(sound)chirp();};
$('download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,world:pet},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mochi-little-world.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>100000)throw Error();const data=JSON.parse(await file.text());if(data.version!==1||!data.world||typeof data.world.name!=='string'||!Number.isFinite(data.world.coins)||!Array.isArray(data.world.owned))throw Error();pet=W.load(data.world);save();render();$('import-message').textContent='Your little world is back!';say('There you are. I saved you a cuddle.');}catch{$('import-message').textContent='That file is not a saved Mochi world. Your current progress is safe.';}$('import').value='';};render();
