(function(root){'use strict';
const items={plant:{name:'Little fern',price:12,slot:'plant'},rug:{name:'Sunshine rug',price:18,slot:'rug'},hat:{name:'Strawberry hat',price:20,slot:'hat'},lamp:{name:'Moon lantern',price:28,slot:'lamp'}};
function fresh(){return {name:'Mochi',fullness:55,energy:65,joy:50,coins:18,xp:0,day:1,tasks:[],owned:[],equipped:[],theme:'meadow',matches:0,badges:[]};}
const clamp=n=>Math.max(0,Math.min(100,n));
function load(raw){const s=fresh();if(!raw||typeof raw!=='object')return s;for(const k of ['fullness','energy','joy'])if(Number.isFinite(raw[k]))s[k]=clamp(Math.round(raw[k]));for(const k of ['coins','xp','day','matches'])if(Number.isInteger(raw[k])&&raw[k]>=0&&raw[k]<=100000)s[k]=raw[k];s.day=Math.max(1,s.day);if(typeof raw.name==='string')s.name=raw.name.trim().slice(0,24)||'Mochi';for(const k of ['tasks','owned','equipped','badges'])if(Array.isArray(raw[k]))s[k]=[...new Set(raw[k].filter(v=>typeof v==='string'))];s.tasks=s.tasks.filter(v=>['feed','rest','cuddle','match'].includes(v));s.owned=s.owned.filter(v=>items[v]);s.equipped=s.equipped.filter(v=>s.owned.includes(v));s.badges=s.badges.filter(v=>['hello','designer','matcher','buddy'].includes(v));if(['meadow','peach','night'].includes(raw.theme))s.theme=raw.theme;return s;}
function badge(s,b){if(!s.badges.includes(b))s.badges.push(b);}
function task(s,t){if(!s.tasks.includes(t)){s.tasks.push(t);s.coins+=3;}if(s.tasks.length===4&&!s.badges.includes('buddy'))badge(s,'buddy');}
function care(s,action){const next=load(s);const field={feed:'fullness',rest:'energy',cuddle:'joy'}[action];if(!field)throw Error('Unknown care');if(next[field]>=100)return {state:next,changed:false};next[field]=clamp(next[field]+(action==='cuddle'?12:25));next.xp+=action==='cuddle'?3:5;task(next,action);if(action==='cuddle')badge(next,'hello');return {state:next,changed:true};}
function matchWin(s){const next=load(s);next.coins+=12;next.xp+=12;next.matches++;next.joy=clamp(next.joy+20);next.energy=clamp(next.energy-12);next.fullness=clamp(next.fullness-8);task(next,'match');badge(next,'matcher');return next;}
function buy(s,id){const next=load(s),item=items[id];if(!item)throw Error('Unknown item');if(next.owned.includes(id)){next.equipped=next.equipped.includes(id)?next.equipped.filter(v=>v!==id):[...next.equipped,id];return {state:next,purchased:false};}if(next.coins<item.price)return {state:next,error:'coins'};next.coins-=item.price;next.owned.push(id);next.equipped.push(id);badge(next,'designer');return {state:next,purchased:true};}
function newDay(s){const next=load(s);if(next.tasks.length!==4)return next;next.day++;next.coins+=10;next.xp+=10;next.tasks=[];next.fullness=Math.max(20,next.fullness-30);next.energy=Math.max(25,next.energy-25);next.joy=Math.max(20,next.joy-15);return next;}
const api={fresh,load,care,matchWin,buy,newDay,items};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.WorldState=api;
})(typeof window!=='undefined'?window:globalThis);
